### ISSUE TITLE
New contact has stopped working

### ISSUE THREAD

**Issue by lukasokoun** [rapidwebltd/php-google-people-api#27] opened 2019-11-05 10:04 UTC
Yesterday, creating a new contact with the error suddenly stopped working:
`PHP Fatal error:  Uncaught exception 'Exception' with message '{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"parent\": Cannot bind query parameter. Field 'parent' could not be found in request message.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"parent\": Cannot bind query parameter. Field 'parent' could not be found in request message."
          }
        ]
      }
    ]
  }
}
' in /var/www/moduly/google/kontakty/vendor/rapidwebltd/php-google-people-api/src/GooglePeople.php:132
Stack trace:
#0 /var/www/moduly/google/kontakty/vendor/rapidwebltd/php-google-people-api/src/Contact.php(16): RapidWeb\GooglePeopleAPI\GooglePeople->save(Object(RapidWeb\GooglePeopleAPI\Contact))
#1 /var/www/ttt.php(24): RapidWeb\GooglePeopleAPI\Contact->save()
#2 {main}
  thrown in /var/www/moduly/google/kontakty/vendor/rapidwebltd/php-google-people-api/src/GooglePeople.php on line 132
`

However, updating the existing contract works!

**Comment by nantoniadis** [comment] 2019-11-05 12:13
I am having the same problem. Something must have changed to the API.

**Comment by Jord-JD** [comment] 2019-11-05 20:58
This looks like a duplicate of #25. If so, this is now fixed. 

Make sure you're on v1.0.1 of this package and try again.

**Comment by lukasokoun** [comment] 2019-11-05 22:30
yes it is it, thank you very much!

**Closed as completed** 2019-11-06 20:42 UTC
